#Please note that currently adding a new package to index bases it off of default
default: https://github.com/CarmeLabs/packages/raw/master/default/packages/default_20180630_171422.zip
jupyter: https://github.com/CarmeLabs/packages/raw/master/jupyter/packages/jupyter_20180628_214331.zip
docker: https://github.com/CarmeLabs/packages/raw/master/docker/packages/docker_20180628_214637.zip
az-bucket: https://github.com/CarmeLabs/packages/raw/master/az-bucket/packages/az-bucket_20180630_190015.zip
az-server: https://github.com/CarmeLabs/packages/raw/master/az-server/packages/az-server_20180630_190152.zip
az-all: ['az-bucket','az-server']
