proxy:
  secretToken: "secret_token"
auth:
  type: github
  github:
    clientId: "clientId"
    clientSecret: "clientsecret"
    callbackUrl: "http://yourhost/hub/oauth_callback"
    org_whitelist:
      - "SomeOrgName"
    scopes:
    - "read:user"
